# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'    
      
      - name: Installing my packages
        working-directory: ./web
        run: yarn install
          

      - name: Build my App
        working-directory: ./web
        run: yarn run build && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.KT_MARKET_BUILD_PAT }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: ./web/out # The folder the action should deploy.
          repository-name: chantulu/kt-market-build
